### PR TITLE
Fixing to make it build in VS 2017 CE

### PR DESCRIPTION
**Pull request by ashalkhakov**
The story goes as follows:

* I decided to follow your StackOverflow answer on building .NET 3.5 CF projects in VS 2017
* you used a preview version of .NET Core SDK and VS 2015 (with project.json)
* this doesn't build on my box with VS 2017

I made some fixes, could you please look at them?

### CODE REVIEW

**Comment by ashalkhakov** [comment]
I had to comment out some of the exception references in the documentation comments -- these don't get resolved with net35-client target framework.

**Comment by skarllot** [comment]
Hi, sorry for taking so long to reply.
- You managed to build on VS 2017?
- I'm aware of exception missing references on XML comments. That's because most classes are compiled inside "Mock" namespace to avoid conflicting with existing classes on net35-client.
- I'm aware of the tests failing on device emulator, that's because of compiler optimizations on Release mode. I have pending tests on real hardware (I'm lacking time).
- I'll try to build on VS 2017 with your changes until Sunday.

Thank you.

**Comment by ashalkhakov** [comment]
What do you think -- is it worth porting other libraries too? I'm very
interested to join the effort of improving the CF ecosystem (we have a
production app at work that we can't drop; it's in need for improvement).

I used your technique in a library with great success (you can see it in
action in RFID Applied organization's InterrogatorLib repo). Thank you very
much for the hints!

30 сент. 2017 г. 11:37 AM пользователь "Fabrício Godoy" <
notifications@github.com> написал:

Merged #1 <https://github.com/skarllot/NETStandard.WindowsCE/pull/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/skarllot/NETStandard.WindowsCE/pull/1#event-1272646855>,
or mute the thread

**Comment by skarllot** [comment]
I think it worth it. I'll try to ensure that existing code is stable before adding more, but I'll accept your merge requests.

I'm interested to join forces too. I'm in same boat, we have a production app that needs improvements and cannot be discarded yet.

I glad that it helped, I was thinking that I was alone in "Compact Framework world" LOL.

**Comment by ashalkhakov** [comment]
Okay, great! Expect some PRs. :)

**Pull request merged**
